<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ScnSocialAuthDoctrineORM\Entity\UserProvider'               => __DIR__ . '/src/ScnSocialAuthDoctrineORM/Entity/UserProvider.php',
    'ScnSocialAuthDoctrineORM\Options\ModuleOptions'             => __DIR__ . '/src/ScnSocialAuthDoctrineORM/Options/ModuleOptions.php',
    'ScnSocialAuthDoctrineORM\Service\UserProviderMapperFactory' => __DIR__ . '/src/ScnSocialAuthDoctrineORM/Service/UserProviderMapperFactory.php',
    'ScnSocialAuthDoctrineORM\Service\ModuleOptionsFactory'      => __DIR__ . '/src/ScnSocialAuthDoctrineORM/Service/ModuleOptionsFactory.php',
    'ScnSocialAuthDoctrineORM\Module'                            => __DIR__ . '/src/ScnSocialAuthDoctrineORM/Module.php',
    'ScnSocialAuthDoctrineORM\Mapper\UserProvider'               => __DIR__ . '/src/ScnSocialAuthDoctrineORM/Mapper/UserProvider.php',
);